# Generated by Django 2.2 on 2019-06-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollow',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
